import { Router } from 'express';
import authRoutes from './authRoutes.js';
import userRoutes from './userRoutes.js';
import studentRoutes from './studentRoutes.js';
import teacherRoutes from './teacherRoutes.js';
import classRoutes from './classRoutes.js';
import admissionRoutes from './admissionRoutes.js';
import noticeRoutes from './noticeRoutes.js';
import eventRoutes from './eventRoutes.js';
import galleryRoutes from './galleryRoutes.js';
import testimonialRoutes from './testimonialRoutes.js';
import contactRoutes from './contactRoutes.js';
import enquiryRoutes from './enquiryRoutes.js';
import resultRoutes from './resultRoutes.js';
import attendanceRoutes from './attendanceRoutes.js';
import feeRoutes from './feeRoutes.js';
import documentRoutes from './documentRoutes.js';
import settingRoutes from './settingRoutes.js';
import dashboardRoutes from './dashboardRoutes.js';
import portalRoutes from './portalRoutes.js';
import parentRoutes from './parentRoutes.js';
import studentPortalRoutes from './studentPortalRoutes.js';
import teacherPortalRoutes from './teacherPortalRoutes.js';
import searchRoutes from './searchRoutes.js';

const router = Router();
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/students', studentRoutes);
router.use('/teachers', teacherRoutes);
router.use('/classes', classRoutes);
router.use('/admissions', admissionRoutes);
router.use('/notices', noticeRoutes);
router.use('/events', eventRoutes);
router.use('/gallery', galleryRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/contact', contactRoutes);
router.use('/enquiries', enquiryRoutes);
router.use('/results', resultRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/fees', feeRoutes);
router.use('/documents', documentRoutes);
router.use('/settings', settingRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/portal', portalRoutes);
router.use('/parent', parentRoutes);
router.use('/student', studentPortalRoutes);
router.use('/teacher', teacherPortalRoutes);
router.use('/search', searchRoutes);
export default router;
